# Generated by Django 3.0.8 on 2020-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_auto_20200814_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='fingerprint',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
