# Generated by Django 3.1.1 on 2020-10-12 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256, null=True)),
                ('thisuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
